/* Generated by Yosys 0.30+48 (git sha1 14d50a176d5, gcc 8.3.1 -fPIC -Os) */

module sync_fifo(wr_en, clk, rst, rd_en, data_in, data_out, full, empty);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  output empty;
  wire empty;
  wire \fifo[0][0] ;
  wire \fifo[0][1] ;
  wire \fifo[0][2] ;
  wire \fifo[0][3] ;
  wire \fifo[0][4] ;
  wire \fifo[0][5] ;
  wire \fifo[0][6] ;
  wire \fifo[0][7] ;
  wire \fifo[1][0] ;
  wire \fifo[1][1] ;
  wire \fifo[1][2] ;
  wire \fifo[1][3] ;
  wire \fifo[1][4] ;
  wire \fifo[1][5] ;
  wire \fifo[1][6] ;
  wire \fifo[1][7] ;
  wire \fifo[2][0] ;
  wire \fifo[2][1] ;
  wire \fifo[2][2] ;
  wire \fifo[2][3] ;
  wire \fifo[2][4] ;
  wire \fifo[2][5] ;
  wire \fifo[2][6] ;
  wire \fifo[2][7] ;
  wire \fifo[3][0] ;
  wire \fifo[3][1] ;
  wire \fifo[3][2] ;
  wire \fifo[3][3] ;
  wire \fifo[3][4] ;
  wire \fifo[3][5] ;
  wire \fifo[3][6] ;
  wire \fifo[3][7] ;
  wire \fifo[4][0] ;
  wire \fifo[4][1] ;
  wire \fifo[4][2] ;
  wire \fifo[4][3] ;
  wire \fifo[4][4] ;
  wire \fifo[4][5] ;
  wire \fifo[4][6] ;
  wire \fifo[4][7] ;
  wire \fifo[5][0] ;
  wire \fifo[5][1] ;
  wire \fifo[5][2] ;
  wire \fifo[5][3] ;
  wire \fifo[5][4] ;
  wire \fifo[5][5] ;
  wire \fifo[5][6] ;
  wire \fifo[5][7] ;
  wire \fifo[6][0] ;
  wire \fifo[6][1] ;
  wire \fifo[6][2] ;
  wire \fifo[6][3] ;
  wire \fifo[6][4] ;
  wire \fifo[6][5] ;
  wire \fifo[6][6] ;
  wire \fifo[6][7] ;
  wire \fifo[7][0] ;
  wire \fifo[7][1] ;
  wire \fifo[7][2] ;
  wire \fifo[7][3] ;
  wire \fifo[7][4] ;
  wire \fifo[7][5] ;
  wire \fifo[7][6] ;
  wire \fifo[7][7] ;
  output full;
  wire full;
  wire \rd_addr[0] ;
  wire \rd_addr[1] ;
  wire \rd_addr[2] ;
  input rd_en;
  wire rd_en;
  wire \rd_ptr[3] ;
  input rst;
  wire rst;
  wire \wr_addr[0] ;
  wire \wr_addr[1] ;
  wire \wr_addr[2] ;
  input wr_en;
  wire wr_en;
  wire \wr_ptr[3] ;
  sky130_fd_sc_hd__buf_1 _223_ (
    .A(\rd_addr[1] ),
    .X(_080_)
  );
  sky130_fd_sc_hd__buf_1 _224_ (
    .A(\rd_addr[0] ),
    .X(_081_)
  );
  sky130_fd_sc_hd__and3_2 _225_ (
    .A(\rd_addr[2] ),
    .B(_080_),
    .C(_081_),
    .X(_082_)
  );
  sky130_fd_sc_hd__buf_1 _226_ (
    .A(_082_),
    .X(_083_)
  );
  sky130_fd_sc_hd__xor2_2 _227_ (
    .A(\rd_ptr[3] ),
    .B(\wr_ptr[3] ),
    .X(_084_)
  );
  sky130_fd_sc_hd__xor2_2 _228_ (
    .A(\rd_addr[0] ),
    .B(\wr_addr[0] ),
    .X(_085_)
  );
  sky130_fd_sc_hd__xor2_2 _229_ (
    .A(\rd_addr[1] ),
    .B(\wr_addr[1] ),
    .X(_086_)
  );
  sky130_fd_sc_hd__xor2_2 _230_ (
    .A(\rd_addr[2] ),
    .B(\wr_addr[2] ),
    .X(_087_)
  );
  sky130_fd_sc_hd__o41a_2 _231_ (
    .A1(_084_),
    .A2(_085_),
    .A3(_086_),
    .A4(_087_),
    .B1(rd_en),
    .X(_088_)
  );
  sky130_fd_sc_hd__nand2_2 _232_ (
    .A(_083_),
    .B(_088_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__xnor2_2 _233_ (
    .A(\rd_ptr[3] ),
    .B(_089_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__and3_2 _234_ (
    .A(_080_),
    .B(_081_),
    .C(_088_),
    .X(_090_)
  );
  sky130_fd_sc_hd__o21a_2 _235_ (
    .A1(\rd_addr[2] ),
    .A2(_090_),
    .B1(_089_),
    .X(_022_)
  );
  sky130_fd_sc_hd__a21oi_2 _236_ (
    .A1(_081_),
    .A2(_088_),
    .B1(_080_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor2_2 _237_ (
    .A(_090_),
    .B(_091_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xor2_2 _238_ (
    .A(_081_),
    .B(_088_),
    .X(_020_)
  );
  sky130_fd_sc_hd__xnor2_2 _239_ (
    .A(\rd_ptr[3] ),
    .B(\wr_ptr[3] ),
    .Y(_092_)
  );
  sky130_fd_sc_hd__o41a_2 _240_ (
    .A1(_092_),
    .A2(_085_),
    .A3(_086_),
    .A4(_087_),
    .B1(wr_en),
    .X(_093_)
  );
  sky130_fd_sc_hd__buf_1 _241_ (
    .A(_093_),
    .X(_094_)
  );
  sky130_fd_sc_hd__and2_2 _242_ (
    .A(\wr_addr[1] ),
    .B(\wr_addr[0] ),
    .X(_095_)
  );
  sky130_fd_sc_hd__and3_2 _243_ (
    .A(\wr_addr[2] ),
    .B(_094_),
    .C(_095_),
    .X(_096_)
  );
  sky130_fd_sc_hd__xor2_2 _244_ (
    .A(\wr_ptr[3] ),
    .B(_096_),
    .X(_019_)
  );
  sky130_fd_sc_hd__a21oi_2 _245_ (
    .A1(_094_),
    .A2(_095_),
    .B1(\wr_addr[2] ),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nor2_2 _246_ (
    .A(_096_),
    .B(_097_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__and2_2 _247_ (
    .A(\wr_addr[0] ),
    .B(_094_),
    .X(_098_)
  );
  sky130_fd_sc_hd__o2bb2a_2 _248_ (
    .A1_N(_094_),
    .A2_N(_095_),
    .B1(_098_),
    .B2(\wr_addr[1] ),
    .X(_017_)
  );
  sky130_fd_sc_hd__nor2_2 _249_ (
    .A(\wr_addr[0] ),
    .B(_094_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_2 _250_ (
    .A(_098_),
    .B(_099_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor3_2 _251_ (
    .A(\rd_addr[2] ),
    .B(_080_),
    .C(_081_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__and3b_2 _252_ (
    .A_N(\rd_addr[2] ),
    .B(_080_),
    .C(_081_),
    .X(_101_)
  );
  sky130_fd_sc_hd__nor3b_2 _253_ (
    .A(\rd_addr[2] ),
    .B(_080_),
    .C_N(\rd_addr[0] ),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor3b_2 _254_ (
    .A(\rd_addr[2] ),
    .B(_081_),
    .C_N(_080_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__a22o_2 _255_ (
    .A1(\fifo[1][3] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][3] ),
    .X(_104_)
  );
  sky130_fd_sc_hd__a221o_2 _256_ (
    .A1(\fifo[7][3] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][3] ),
    .C1(_104_),
    .X(_105_)
  );
  sky130_fd_sc_hd__and3b_2 _257_ (
    .A_N(_081_),
    .B(_080_),
    .C(\rd_addr[2] ),
    .X(_106_)
  );
  sky130_fd_sc_hd__and3b_2 _258_ (
    .A_N(_080_),
    .B(_081_),
    .C(\rd_addr[2] ),
    .X(_107_)
  );
  sky130_fd_sc_hd__nor3b_2 _259_ (
    .A(_080_),
    .B(_081_),
    .C_N(\rd_addr[2] ),
    .Y(_108_)
  );
  sky130_fd_sc_hd__a22o_2 _260_ (
    .A1(\fifo[5][3] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][3] ),
    .X(_109_)
  );
  sky130_fd_sc_hd__a21o_2 _261_ (
    .A1(\fifo[6][3] ),
    .A2(_106_),
    .B1(_109_),
    .X(_110_)
  );
  sky130_fd_sc_hd__a211o_2 _262_ (
    .A1(\fifo[0][3] ),
    .A2(_100_),
    .B1(_105_),
    .C1(_110_),
    .X(data_out[3])
  );
  sky130_fd_sc_hd__a22o_2 _263_ (
    .A1(\fifo[5][4] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][4] ),
    .X(_111_)
  );
  sky130_fd_sc_hd__a21o_2 _264_ (
    .A1(\fifo[6][4] ),
    .A2(_106_),
    .B1(_111_),
    .X(_112_)
  );
  sky130_fd_sc_hd__a22o_2 _265_ (
    .A1(\fifo[1][4] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][4] ),
    .X(_113_)
  );
  sky130_fd_sc_hd__a221o_2 _266_ (
    .A1(\fifo[7][4] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][4] ),
    .C1(_113_),
    .X(_114_)
  );
  sky130_fd_sc_hd__a211o_2 _267_ (
    .A1(\fifo[0][4] ),
    .A2(_100_),
    .B1(_112_),
    .C1(_114_),
    .X(data_out[4])
  );
  sky130_fd_sc_hd__a22o_2 _268_ (
    .A1(\fifo[5][5] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][5] ),
    .X(_115_)
  );
  sky130_fd_sc_hd__a21o_2 _269_ (
    .A1(\fifo[6][5] ),
    .A2(_106_),
    .B1(_115_),
    .X(_116_)
  );
  sky130_fd_sc_hd__a22o_2 _270_ (
    .A1(\fifo[1][5] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][5] ),
    .X(_117_)
  );
  sky130_fd_sc_hd__a221o_2 _271_ (
    .A1(\fifo[7][5] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][5] ),
    .C1(_117_),
    .X(_118_)
  );
  sky130_fd_sc_hd__a211o_2 _272_ (
    .A1(\fifo[0][5] ),
    .A2(_100_),
    .B1(_116_),
    .C1(_118_),
    .X(data_out[5])
  );
  sky130_fd_sc_hd__a22o_2 _273_ (
    .A1(\fifo[5][6] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][6] ),
    .X(_119_)
  );
  sky130_fd_sc_hd__a21o_2 _274_ (
    .A1(\fifo[6][6] ),
    .A2(_106_),
    .B1(_119_),
    .X(_120_)
  );
  sky130_fd_sc_hd__a22o_2 _275_ (
    .A1(\fifo[1][6] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][6] ),
    .X(_121_)
  );
  sky130_fd_sc_hd__a221o_2 _276_ (
    .A1(\fifo[7][6] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][6] ),
    .C1(_121_),
    .X(_122_)
  );
  sky130_fd_sc_hd__a211o_2 _277_ (
    .A1(\fifo[0][6] ),
    .A2(_100_),
    .B1(_120_),
    .C1(_122_),
    .X(data_out[6])
  );
  sky130_fd_sc_hd__a22o_2 _278_ (
    .A1(\fifo[5][7] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][7] ),
    .X(_123_)
  );
  sky130_fd_sc_hd__a21o_2 _279_ (
    .A1(\fifo[6][7] ),
    .A2(_106_),
    .B1(_123_),
    .X(_124_)
  );
  sky130_fd_sc_hd__a22o_2 _280_ (
    .A1(\fifo[1][7] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][7] ),
    .X(_125_)
  );
  sky130_fd_sc_hd__a221o_2 _281_ (
    .A1(\fifo[7][7] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][7] ),
    .C1(_125_),
    .X(_126_)
  );
  sky130_fd_sc_hd__a211o_2 _282_ (
    .A1(\fifo[0][7] ),
    .A2(_100_),
    .B1(_124_),
    .C1(_126_),
    .X(data_out[7])
  );
  sky130_fd_sc_hd__or3_2 _283_ (
    .A(_085_),
    .B(_086_),
    .C(_087_),
    .X(_127_)
  );
  sky130_fd_sc_hd__nor2_2 _284_ (
    .A(_084_),
    .B(_127_),
    .Y(empty)
  );
  sky130_fd_sc_hd__nor2_2 _285_ (
    .A(_092_),
    .B(_127_),
    .Y(full)
  );
  sky130_fd_sc_hd__a22o_2 _286_ (
    .A1(\fifo[5][0] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][0] ),
    .X(_128_)
  );
  sky130_fd_sc_hd__a21o_2 _287_ (
    .A1(\fifo[6][0] ),
    .A2(_106_),
    .B1(_128_),
    .X(_129_)
  );
  sky130_fd_sc_hd__a22o_2 _288_ (
    .A1(\fifo[1][0] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][0] ),
    .X(_130_)
  );
  sky130_fd_sc_hd__a221o_2 _289_ (
    .A1(\fifo[7][0] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][0] ),
    .C1(_130_),
    .X(_131_)
  );
  sky130_fd_sc_hd__a211o_2 _290_ (
    .A1(\fifo[0][0] ),
    .A2(_100_),
    .B1(_129_),
    .C1(_131_),
    .X(data_out[0])
  );
  sky130_fd_sc_hd__a22o_2 _291_ (
    .A1(\fifo[5][1] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][1] ),
    .X(_132_)
  );
  sky130_fd_sc_hd__a21o_2 _292_ (
    .A1(\fifo[6][1] ),
    .A2(_106_),
    .B1(_132_),
    .X(_133_)
  );
  sky130_fd_sc_hd__a22o_2 _293_ (
    .A1(\fifo[1][1] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][1] ),
    .X(_134_)
  );
  sky130_fd_sc_hd__a221o_2 _294_ (
    .A1(\fifo[7][1] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][1] ),
    .C1(_134_),
    .X(_135_)
  );
  sky130_fd_sc_hd__a211o_2 _295_ (
    .A1(\fifo[0][1] ),
    .A2(_100_),
    .B1(_133_),
    .C1(_135_),
    .X(data_out[1])
  );
  sky130_fd_sc_hd__a22o_2 _296_ (
    .A1(\fifo[5][2] ),
    .A2(_107_),
    .B1(_108_),
    .B2(\fifo[4][2] ),
    .X(_136_)
  );
  sky130_fd_sc_hd__a21o_2 _297_ (
    .A1(\fifo[6][2] ),
    .A2(_106_),
    .B1(_136_),
    .X(_137_)
  );
  sky130_fd_sc_hd__a22o_2 _298_ (
    .A1(\fifo[1][2] ),
    .A2(_102_),
    .B1(_103_),
    .B2(\fifo[2][2] ),
    .X(_138_)
  );
  sky130_fd_sc_hd__a221o_2 _299_ (
    .A1(\fifo[7][2] ),
    .A2(_083_),
    .B1(_101_),
    .B2(\fifo[3][2] ),
    .C1(_138_),
    .X(_139_)
  );
  sky130_fd_sc_hd__a211o_2 _300_ (
    .A1(\fifo[0][2] ),
    .A2(_100_),
    .B1(_137_),
    .C1(_139_),
    .X(data_out[2])
  );
  sky130_fd_sc_hd__inv_2 _301_ (
    .A(rst),
    .Y(_000_)
  );
  sky130_fd_sc_hd__and2_2 _302_ (
    .A(\wr_addr[2] ),
    .B(_000_),
    .X(_140_)
  );
  sky130_fd_sc_hd__and3_2 _303_ (
    .A(_094_),
    .B(_095_),
    .C(_140_),
    .X(_141_)
  );
  sky130_fd_sc_hd__buf_1 _304_ (
    .A(_141_),
    .X(_142_)
  );
  sky130_fd_sc_hd__mux2_2 _305_ (
    .A0(\fifo[7][0] ),
    .A1(data_in[0]),
    .S(_142_),
    .X(_143_)
  );
  sky130_fd_sc_hd__buf_1 _306_ (
    .A(_143_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_2 _307_ (
    .A0(\fifo[7][1] ),
    .A1(data_in[1]),
    .S(_142_),
    .X(_144_)
  );
  sky130_fd_sc_hd__buf_1 _308_ (
    .A(_144_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_2 _309_ (
    .A0(\fifo[7][2] ),
    .A1(data_in[2]),
    .S(_142_),
    .X(_145_)
  );
  sky130_fd_sc_hd__buf_1 _310_ (
    .A(_145_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_2 _311_ (
    .A0(\fifo[7][3] ),
    .A1(data_in[3]),
    .S(_142_),
    .X(_146_)
  );
  sky130_fd_sc_hd__buf_1 _312_ (
    .A(_146_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_2 _313_ (
    .A0(\fifo[7][4] ),
    .A1(data_in[4]),
    .S(_142_),
    .X(_147_)
  );
  sky130_fd_sc_hd__buf_1 _314_ (
    .A(_147_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_2 _315_ (
    .A0(\fifo[7][5] ),
    .A1(data_in[5]),
    .S(_142_),
    .X(_148_)
  );
  sky130_fd_sc_hd__buf_1 _316_ (
    .A(_148_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_2 _317_ (
    .A0(\fifo[7][6] ),
    .A1(data_in[6]),
    .S(_142_),
    .X(_149_)
  );
  sky130_fd_sc_hd__buf_1 _318_ (
    .A(_149_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_2 _319_ (
    .A0(\fifo[7][7] ),
    .A1(data_in[7]),
    .S(_142_),
    .X(_150_)
  );
  sky130_fd_sc_hd__buf_1 _320_ (
    .A(_150_),
    .X(_015_)
  );
  sky130_fd_sc_hd__inv_2 _321_ (
    .A(rst),
    .Y(_001_)
  );
  sky130_fd_sc_hd__inv_2 _322_ (
    .A(rst),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_2 _323_ (
    .A(rst),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_2 _324_ (
    .A(rst),
    .Y(_004_)
  );
  sky130_fd_sc_hd__inv_2 _325_ (
    .A(rst),
    .Y(_005_)
  );
  sky130_fd_sc_hd__inv_2 _326_ (
    .A(rst),
    .Y(_006_)
  );
  sky130_fd_sc_hd__inv_2 _327_ (
    .A(rst),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_2 _328_ (
    .A(\wr_addr[2] ),
    .B(rst),
    .Y(_151_)
  );
  sky130_fd_sc_hd__nor2_2 _329_ (
    .A(\wr_addr[1] ),
    .B(\wr_addr[0] ),
    .Y(_152_)
  );
  sky130_fd_sc_hd__and3_2 _330_ (
    .A(_094_),
    .B(_151_),
    .C(_152_),
    .X(_153_)
  );
  sky130_fd_sc_hd__buf_1 _331_ (
    .A(_153_),
    .X(_154_)
  );
  sky130_fd_sc_hd__mux2_2 _332_ (
    .A0(\fifo[0][0] ),
    .A1(data_in[0]),
    .S(_154_),
    .X(_155_)
  );
  sky130_fd_sc_hd__buf_1 _333_ (
    .A(_155_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_2 _334_ (
    .A0(\fifo[0][1] ),
    .A1(data_in[1]),
    .S(_154_),
    .X(_156_)
  );
  sky130_fd_sc_hd__buf_1 _335_ (
    .A(_156_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_2 _336_ (
    .A0(\fifo[0][2] ),
    .A1(data_in[2]),
    .S(_154_),
    .X(_157_)
  );
  sky130_fd_sc_hd__buf_1 _337_ (
    .A(_157_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_2 _338_ (
    .A0(\fifo[0][3] ),
    .A1(data_in[3]),
    .S(_154_),
    .X(_158_)
  );
  sky130_fd_sc_hd__buf_1 _339_ (
    .A(_158_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_2 _340_ (
    .A0(\fifo[0][4] ),
    .A1(data_in[4]),
    .S(_154_),
    .X(_159_)
  );
  sky130_fd_sc_hd__buf_1 _341_ (
    .A(_159_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_2 _342_ (
    .A0(\fifo[0][5] ),
    .A1(data_in[5]),
    .S(_154_),
    .X(_160_)
  );
  sky130_fd_sc_hd__buf_1 _343_ (
    .A(_160_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_2 _344_ (
    .A0(\fifo[0][6] ),
    .A1(data_in[6]),
    .S(_154_),
    .X(_161_)
  );
  sky130_fd_sc_hd__buf_1 _345_ (
    .A(_161_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_2 _346_ (
    .A0(\fifo[0][7] ),
    .A1(data_in[7]),
    .S(_154_),
    .X(_162_)
  );
  sky130_fd_sc_hd__buf_1 _347_ (
    .A(_162_),
    .X(_031_)
  );
  sky130_fd_sc_hd__and4b_2 _348_ (
    .A_N(\wr_addr[1] ),
    .B(\wr_addr[0] ),
    .C(_093_),
    .D(_151_),
    .X(_163_)
  );
  sky130_fd_sc_hd__buf_1 _349_ (
    .A(_163_),
    .X(_164_)
  );
  sky130_fd_sc_hd__mux2_2 _350_ (
    .A0(\fifo[1][0] ),
    .A1(data_in[0]),
    .S(_164_),
    .X(_165_)
  );
  sky130_fd_sc_hd__buf_1 _351_ (
    .A(_165_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_2 _352_ (
    .A0(\fifo[1][1] ),
    .A1(data_in[1]),
    .S(_164_),
    .X(_166_)
  );
  sky130_fd_sc_hd__buf_1 _353_ (
    .A(_166_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_2 _354_ (
    .A0(\fifo[1][2] ),
    .A1(data_in[2]),
    .S(_164_),
    .X(_167_)
  );
  sky130_fd_sc_hd__buf_1 _355_ (
    .A(_167_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_2 _356_ (
    .A0(\fifo[1][3] ),
    .A1(data_in[3]),
    .S(_164_),
    .X(_168_)
  );
  sky130_fd_sc_hd__buf_1 _357_ (
    .A(_168_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_2 _358_ (
    .A0(\fifo[1][4] ),
    .A1(data_in[4]),
    .S(_164_),
    .X(_169_)
  );
  sky130_fd_sc_hd__buf_1 _359_ (
    .A(_169_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_2 _360_ (
    .A0(\fifo[1][5] ),
    .A1(data_in[5]),
    .S(_164_),
    .X(_170_)
  );
  sky130_fd_sc_hd__buf_1 _361_ (
    .A(_170_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_2 _362_ (
    .A0(\fifo[1][6] ),
    .A1(data_in[6]),
    .S(_164_),
    .X(_171_)
  );
  sky130_fd_sc_hd__buf_1 _363_ (
    .A(_171_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_2 _364_ (
    .A0(\fifo[1][7] ),
    .A1(data_in[7]),
    .S(_164_),
    .X(_172_)
  );
  sky130_fd_sc_hd__buf_1 _365_ (
    .A(_172_),
    .X(_039_)
  );
  sky130_fd_sc_hd__and4b_2 _366_ (
    .A_N(\wr_addr[0] ),
    .B(_094_),
    .C(_151_),
    .D(\wr_addr[1] ),
    .X(_173_)
  );
  sky130_fd_sc_hd__buf_1 _367_ (
    .A(_173_),
    .X(_174_)
  );
  sky130_fd_sc_hd__mux2_2 _368_ (
    .A0(\fifo[2][0] ),
    .A1(data_in[0]),
    .S(_174_),
    .X(_175_)
  );
  sky130_fd_sc_hd__buf_1 _369_ (
    .A(_175_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_2 _370_ (
    .A0(\fifo[2][1] ),
    .A1(data_in[1]),
    .S(_174_),
    .X(_176_)
  );
  sky130_fd_sc_hd__buf_1 _371_ (
    .A(_176_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_2 _372_ (
    .A0(\fifo[2][2] ),
    .A1(data_in[2]),
    .S(_174_),
    .X(_177_)
  );
  sky130_fd_sc_hd__buf_1 _373_ (
    .A(_177_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_2 _374_ (
    .A0(\fifo[2][3] ),
    .A1(data_in[3]),
    .S(_174_),
    .X(_178_)
  );
  sky130_fd_sc_hd__buf_1 _375_ (
    .A(_178_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_2 _376_ (
    .A0(\fifo[2][4] ),
    .A1(data_in[4]),
    .S(_174_),
    .X(_179_)
  );
  sky130_fd_sc_hd__buf_1 _377_ (
    .A(_179_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_2 _378_ (
    .A0(\fifo[2][5] ),
    .A1(data_in[5]),
    .S(_174_),
    .X(_180_)
  );
  sky130_fd_sc_hd__buf_1 _379_ (
    .A(_180_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_2 _380_ (
    .A0(\fifo[2][6] ),
    .A1(data_in[6]),
    .S(_174_),
    .X(_181_)
  );
  sky130_fd_sc_hd__buf_1 _381_ (
    .A(_181_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_2 _382_ (
    .A0(\fifo[2][7] ),
    .A1(data_in[7]),
    .S(_174_),
    .X(_182_)
  );
  sky130_fd_sc_hd__buf_1 _383_ (
    .A(_182_),
    .X(_047_)
  );
  sky130_fd_sc_hd__and3_2 _384_ (
    .A(_094_),
    .B(_095_),
    .C(_151_),
    .X(_183_)
  );
  sky130_fd_sc_hd__buf_1 _385_ (
    .A(_183_),
    .X(_184_)
  );
  sky130_fd_sc_hd__mux2_2 _386_ (
    .A0(\fifo[3][0] ),
    .A1(data_in[0]),
    .S(_184_),
    .X(_185_)
  );
  sky130_fd_sc_hd__buf_1 _387_ (
    .A(_185_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_2 _388_ (
    .A0(\fifo[3][1] ),
    .A1(data_in[1]),
    .S(_184_),
    .X(_186_)
  );
  sky130_fd_sc_hd__buf_1 _389_ (
    .A(_186_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_2 _390_ (
    .A0(\fifo[3][2] ),
    .A1(data_in[2]),
    .S(_184_),
    .X(_187_)
  );
  sky130_fd_sc_hd__buf_1 _391_ (
    .A(_187_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_2 _392_ (
    .A0(\fifo[3][3] ),
    .A1(data_in[3]),
    .S(_184_),
    .X(_188_)
  );
  sky130_fd_sc_hd__buf_1 _393_ (
    .A(_188_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_2 _394_ (
    .A0(\fifo[3][4] ),
    .A1(data_in[4]),
    .S(_184_),
    .X(_189_)
  );
  sky130_fd_sc_hd__buf_1 _395_ (
    .A(_189_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_2 _396_ (
    .A0(\fifo[3][5] ),
    .A1(data_in[5]),
    .S(_184_),
    .X(_190_)
  );
  sky130_fd_sc_hd__buf_1 _397_ (
    .A(_190_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_2 _398_ (
    .A0(\fifo[3][6] ),
    .A1(data_in[6]),
    .S(_184_),
    .X(_191_)
  );
  sky130_fd_sc_hd__buf_1 _399_ (
    .A(_191_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_2 _400_ (
    .A0(\fifo[3][7] ),
    .A1(data_in[7]),
    .S(_184_),
    .X(_192_)
  );
  sky130_fd_sc_hd__buf_1 _401_ (
    .A(_192_),
    .X(_055_)
  );
  sky130_fd_sc_hd__and3_2 _402_ (
    .A(_094_),
    .B(_140_),
    .C(_152_),
    .X(_193_)
  );
  sky130_fd_sc_hd__buf_1 _403_ (
    .A(_193_),
    .X(_194_)
  );
  sky130_fd_sc_hd__mux2_2 _404_ (
    .A0(\fifo[4][0] ),
    .A1(data_in[0]),
    .S(_194_),
    .X(_195_)
  );
  sky130_fd_sc_hd__buf_1 _405_ (
    .A(_195_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_2 _406_ (
    .A0(\fifo[4][1] ),
    .A1(data_in[1]),
    .S(_194_),
    .X(_196_)
  );
  sky130_fd_sc_hd__buf_1 _407_ (
    .A(_196_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_2 _408_ (
    .A0(\fifo[4][2] ),
    .A1(data_in[2]),
    .S(_194_),
    .X(_197_)
  );
  sky130_fd_sc_hd__buf_1 _409_ (
    .A(_197_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_2 _410_ (
    .A0(\fifo[4][3] ),
    .A1(data_in[3]),
    .S(_194_),
    .X(_198_)
  );
  sky130_fd_sc_hd__buf_1 _411_ (
    .A(_198_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_2 _412_ (
    .A0(\fifo[4][4] ),
    .A1(data_in[4]),
    .S(_194_),
    .X(_199_)
  );
  sky130_fd_sc_hd__buf_1 _413_ (
    .A(_199_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_2 _414_ (
    .A0(\fifo[4][5] ),
    .A1(data_in[5]),
    .S(_194_),
    .X(_200_)
  );
  sky130_fd_sc_hd__buf_1 _415_ (
    .A(_200_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_2 _416_ (
    .A0(\fifo[4][6] ),
    .A1(data_in[6]),
    .S(_194_),
    .X(_201_)
  );
  sky130_fd_sc_hd__buf_1 _417_ (
    .A(_201_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_2 _418_ (
    .A0(\fifo[4][7] ),
    .A1(data_in[7]),
    .S(_194_),
    .X(_202_)
  );
  sky130_fd_sc_hd__buf_1 _419_ (
    .A(_202_),
    .X(_063_)
  );
  sky130_fd_sc_hd__and4b_2 _420_ (
    .A_N(\wr_addr[1] ),
    .B(\wr_addr[0] ),
    .C(_093_),
    .D(_140_),
    .X(_203_)
  );
  sky130_fd_sc_hd__buf_1 _421_ (
    .A(_203_),
    .X(_204_)
  );
  sky130_fd_sc_hd__mux2_2 _422_ (
    .A0(\fifo[5][0] ),
    .A1(data_in[0]),
    .S(_204_),
    .X(_205_)
  );
  sky130_fd_sc_hd__buf_1 _423_ (
    .A(_205_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_2 _424_ (
    .A0(\fifo[5][1] ),
    .A1(data_in[1]),
    .S(_204_),
    .X(_206_)
  );
  sky130_fd_sc_hd__buf_1 _425_ (
    .A(_206_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_2 _426_ (
    .A0(\fifo[5][2] ),
    .A1(data_in[2]),
    .S(_204_),
    .X(_207_)
  );
  sky130_fd_sc_hd__buf_1 _427_ (
    .A(_207_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_2 _428_ (
    .A0(\fifo[5][3] ),
    .A1(data_in[3]),
    .S(_204_),
    .X(_208_)
  );
  sky130_fd_sc_hd__buf_1 _429_ (
    .A(_208_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_2 _430_ (
    .A0(\fifo[5][4] ),
    .A1(data_in[4]),
    .S(_204_),
    .X(_209_)
  );
  sky130_fd_sc_hd__buf_1 _431_ (
    .A(_209_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_2 _432_ (
    .A0(\fifo[5][5] ),
    .A1(data_in[5]),
    .S(_204_),
    .X(_210_)
  );
  sky130_fd_sc_hd__buf_1 _433_ (
    .A(_210_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_2 _434_ (
    .A0(\fifo[5][6] ),
    .A1(data_in[6]),
    .S(_204_),
    .X(_211_)
  );
  sky130_fd_sc_hd__buf_1 _435_ (
    .A(_211_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_2 _436_ (
    .A0(\fifo[5][7] ),
    .A1(data_in[7]),
    .S(_204_),
    .X(_212_)
  );
  sky130_fd_sc_hd__buf_1 _437_ (
    .A(_212_),
    .X(_071_)
  );
  sky130_fd_sc_hd__and4b_2 _438_ (
    .A_N(\wr_addr[0] ),
    .B(_093_),
    .C(_140_),
    .D(\wr_addr[1] ),
    .X(_213_)
  );
  sky130_fd_sc_hd__buf_1 _439_ (
    .A(_213_),
    .X(_214_)
  );
  sky130_fd_sc_hd__mux2_2 _440_ (
    .A0(\fifo[6][0] ),
    .A1(data_in[0]),
    .S(_214_),
    .X(_215_)
  );
  sky130_fd_sc_hd__buf_1 _441_ (
    .A(_215_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_2 _442_ (
    .A0(\fifo[6][1] ),
    .A1(data_in[1]),
    .S(_214_),
    .X(_216_)
  );
  sky130_fd_sc_hd__buf_1 _443_ (
    .A(_216_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_2 _444_ (
    .A0(\fifo[6][2] ),
    .A1(data_in[2]),
    .S(_214_),
    .X(_217_)
  );
  sky130_fd_sc_hd__buf_1 _445_ (
    .A(_217_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_2 _446_ (
    .A0(\fifo[6][3] ),
    .A1(data_in[3]),
    .S(_214_),
    .X(_218_)
  );
  sky130_fd_sc_hd__buf_1 _447_ (
    .A(_218_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_2 _448_ (
    .A0(\fifo[6][4] ),
    .A1(data_in[4]),
    .S(_214_),
    .X(_219_)
  );
  sky130_fd_sc_hd__buf_1 _449_ (
    .A(_219_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_2 _450_ (
    .A0(\fifo[6][5] ),
    .A1(data_in[5]),
    .S(_214_),
    .X(_220_)
  );
  sky130_fd_sc_hd__buf_1 _451_ (
    .A(_220_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_2 _452_ (
    .A0(\fifo[6][6] ),
    .A1(data_in[6]),
    .S(_214_),
    .X(_221_)
  );
  sky130_fd_sc_hd__buf_1 _453_ (
    .A(_221_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_2 _454_ (
    .A0(\fifo[6][7] ),
    .A1(data_in[7]),
    .S(_214_),
    .X(_222_)
  );
  sky130_fd_sc_hd__buf_1 _455_ (
    .A(_222_),
    .X(_079_)
  );
  sky130_fd_sc_hd__dfxtp_2 _456_ (
    .CLK(clk),
    .D(_008_),
    .Q(\fifo[7][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _457_ (
    .CLK(clk),
    .D(_009_),
    .Q(\fifo[7][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _458_ (
    .CLK(clk),
    .D(_010_),
    .Q(\fifo[7][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _459_ (
    .CLK(clk),
    .D(_011_),
    .Q(\fifo[7][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _460_ (
    .CLK(clk),
    .D(_012_),
    .Q(\fifo[7][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _461_ (
    .CLK(clk),
    .D(_013_),
    .Q(\fifo[7][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _462_ (
    .CLK(clk),
    .D(_014_),
    .Q(\fifo[7][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _463_ (
    .CLK(clk),
    .D(_015_),
    .Q(\fifo[7][7] )
  );
  sky130_fd_sc_hd__dfrtp_2 _464_ (
    .CLK(clk),
    .D(_016_),
    .Q(\wr_addr[0] ),
    .RESET_B(_000_)
  );
  sky130_fd_sc_hd__dfrtp_2 _465_ (
    .CLK(clk),
    .D(_017_),
    .Q(\wr_addr[1] ),
    .RESET_B(_001_)
  );
  sky130_fd_sc_hd__dfrtp_2 _466_ (
    .CLK(clk),
    .D(_018_),
    .Q(\wr_addr[2] ),
    .RESET_B(_002_)
  );
  sky130_fd_sc_hd__dfrtp_2 _467_ (
    .CLK(clk),
    .D(_019_),
    .Q(\wr_ptr[3] ),
    .RESET_B(_003_)
  );
  sky130_fd_sc_hd__dfrtp_2 _468_ (
    .CLK(clk),
    .D(_020_),
    .Q(\rd_addr[0] ),
    .RESET_B(_004_)
  );
  sky130_fd_sc_hd__dfrtp_2 _469_ (
    .CLK(clk),
    .D(_021_),
    .Q(\rd_addr[1] ),
    .RESET_B(_005_)
  );
  sky130_fd_sc_hd__dfrtp_2 _470_ (
    .CLK(clk),
    .D(_022_),
    .Q(\rd_addr[2] ),
    .RESET_B(_006_)
  );
  sky130_fd_sc_hd__dfrtp_2 _471_ (
    .CLK(clk),
    .D(_023_),
    .Q(\rd_ptr[3] ),
    .RESET_B(_007_)
  );
  sky130_fd_sc_hd__dfxtp_2 _472_ (
    .CLK(clk),
    .D(_024_),
    .Q(\fifo[0][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _473_ (
    .CLK(clk),
    .D(_025_),
    .Q(\fifo[0][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _474_ (
    .CLK(clk),
    .D(_026_),
    .Q(\fifo[0][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _475_ (
    .CLK(clk),
    .D(_027_),
    .Q(\fifo[0][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _476_ (
    .CLK(clk),
    .D(_028_),
    .Q(\fifo[0][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _477_ (
    .CLK(clk),
    .D(_029_),
    .Q(\fifo[0][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _478_ (
    .CLK(clk),
    .D(_030_),
    .Q(\fifo[0][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _479_ (
    .CLK(clk),
    .D(_031_),
    .Q(\fifo[0][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _480_ (
    .CLK(clk),
    .D(_032_),
    .Q(\fifo[1][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _481_ (
    .CLK(clk),
    .D(_033_),
    .Q(\fifo[1][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _482_ (
    .CLK(clk),
    .D(_034_),
    .Q(\fifo[1][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _483_ (
    .CLK(clk),
    .D(_035_),
    .Q(\fifo[1][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _484_ (
    .CLK(clk),
    .D(_036_),
    .Q(\fifo[1][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _485_ (
    .CLK(clk),
    .D(_037_),
    .Q(\fifo[1][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _486_ (
    .CLK(clk),
    .D(_038_),
    .Q(\fifo[1][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _487_ (
    .CLK(clk),
    .D(_039_),
    .Q(\fifo[1][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _488_ (
    .CLK(clk),
    .D(_040_),
    .Q(\fifo[2][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _489_ (
    .CLK(clk),
    .D(_041_),
    .Q(\fifo[2][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _490_ (
    .CLK(clk),
    .D(_042_),
    .Q(\fifo[2][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _491_ (
    .CLK(clk),
    .D(_043_),
    .Q(\fifo[2][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _492_ (
    .CLK(clk),
    .D(_044_),
    .Q(\fifo[2][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _493_ (
    .CLK(clk),
    .D(_045_),
    .Q(\fifo[2][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _494_ (
    .CLK(clk),
    .D(_046_),
    .Q(\fifo[2][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _495_ (
    .CLK(clk),
    .D(_047_),
    .Q(\fifo[2][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _496_ (
    .CLK(clk),
    .D(_048_),
    .Q(\fifo[3][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _497_ (
    .CLK(clk),
    .D(_049_),
    .Q(\fifo[3][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _498_ (
    .CLK(clk),
    .D(_050_),
    .Q(\fifo[3][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _499_ (
    .CLK(clk),
    .D(_051_),
    .Q(\fifo[3][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _500_ (
    .CLK(clk),
    .D(_052_),
    .Q(\fifo[3][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _501_ (
    .CLK(clk),
    .D(_053_),
    .Q(\fifo[3][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _502_ (
    .CLK(clk),
    .D(_054_),
    .Q(\fifo[3][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _503_ (
    .CLK(clk),
    .D(_055_),
    .Q(\fifo[3][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _504_ (
    .CLK(clk),
    .D(_056_),
    .Q(\fifo[4][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _505_ (
    .CLK(clk),
    .D(_057_),
    .Q(\fifo[4][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _506_ (
    .CLK(clk),
    .D(_058_),
    .Q(\fifo[4][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _507_ (
    .CLK(clk),
    .D(_059_),
    .Q(\fifo[4][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _508_ (
    .CLK(clk),
    .D(_060_),
    .Q(\fifo[4][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _509_ (
    .CLK(clk),
    .D(_061_),
    .Q(\fifo[4][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _510_ (
    .CLK(clk),
    .D(_062_),
    .Q(\fifo[4][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _511_ (
    .CLK(clk),
    .D(_063_),
    .Q(\fifo[4][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _512_ (
    .CLK(clk),
    .D(_064_),
    .Q(\fifo[5][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _513_ (
    .CLK(clk),
    .D(_065_),
    .Q(\fifo[5][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _514_ (
    .CLK(clk),
    .D(_066_),
    .Q(\fifo[5][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _515_ (
    .CLK(clk),
    .D(_067_),
    .Q(\fifo[5][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _516_ (
    .CLK(clk),
    .D(_068_),
    .Q(\fifo[5][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _517_ (
    .CLK(clk),
    .D(_069_),
    .Q(\fifo[5][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _518_ (
    .CLK(clk),
    .D(_070_),
    .Q(\fifo[5][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _519_ (
    .CLK(clk),
    .D(_071_),
    .Q(\fifo[5][7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _520_ (
    .CLK(clk),
    .D(_072_),
    .Q(\fifo[6][0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _521_ (
    .CLK(clk),
    .D(_073_),
    .Q(\fifo[6][1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _522_ (
    .CLK(clk),
    .D(_074_),
    .Q(\fifo[6][2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _523_ (
    .CLK(clk),
    .D(_075_),
    .Q(\fifo[6][3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _524_ (
    .CLK(clk),
    .D(_076_),
    .Q(\fifo[6][4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _525_ (
    .CLK(clk),
    .D(_077_),
    .Q(\fifo[6][5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _526_ (
    .CLK(clk),
    .D(_078_),
    .Q(\fifo[6][6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _527_ (
    .CLK(clk),
    .D(_079_),
    .Q(\fifo[6][7] )
  );
endmodule
